name: CD Bookstore

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and Cache Dependencies
        uses: ./.github/workflows/actions/setup-node-and-cache

      - name: Lint, Prettify, and Test
        uses: ./.github/workflows/actions/lint-and-prettify-and-test

      - name: Deploy to [undefined]
        run: echo "Deploying to [undefined]... 🚀"
